<?php

use Illuminate\Database\Seeder;

class GeneratedMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-07-24 08:13:24',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-03-07 21:36:16',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-03-07 21:36:16',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 21,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-05-09 10:37:12',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-29 05:48:15',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-29 05:48:15',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-29 05:48:15',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 22,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2019-03-07 21:39:40',
                'updated_at' => '2019-08-29 05:48:15',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Partner Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => 32,
                'order' => 1,
                'created_at' => '2019-05-08 12:05:08',
                'updated_at' => '2019-05-09 11:12:52',
                'route' => 'voyager.partner-types.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Partner',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => '#000000',
                'parent_id' => 32,
                'order' => 2,
                'created_at' => '2019-05-08 12:05:08',
                'updated_at' => '2019-05-09 14:10:00',
                'route' => 'voyager.partner2.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'About GIC',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-question',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-05-09 10:35:04',
                'updated_at' => '2019-05-09 10:38:46',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Social Medias',
                'url' => '/admin/about-us-link',
                'target' => '_self',
                'icon_class' => 'voyager-facebook',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2019-05-09 10:37:05',
                'updated_at' => '2019-05-09 10:37:13',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'News',
                'url' => '/admin/news',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2019-05-09 10:42:30',
                'updated_at' => '2019-06-10 21:26:49',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Seminars',
                'url' => '/admin/events',
                'target' => '_self',
                'icon_class' => 'voyager-tv',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2019-05-09 10:43:46',
                'updated_at' => '2019-06-10 21:26:49',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Students & Alumni',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2019-05-09 10:44:38',
                'updated_at' => '2019-06-10 21:26:49',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Alumni/Student',
                'url' => '/admin/aluminus',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 1,
                'created_at' => '2019-05-09 10:44:58',
                'updated_at' => '2019-08-28 14:55:56',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Faculty & Staff',
                'url' => '/admin/faculty-and-staff',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-05-09 10:46:10',
                'updated_at' => '2019-06-04 22:30:23',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Academic Programs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2019-05-09 10:46:40',
                'updated_at' => '2019-06-09 12:31:00',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'GIC Research',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lab',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2019-05-09 10:47:07',
                'updated_at' => '2019-06-04 22:30:10',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Projects',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-05-09 10:48:33',
                'updated_at' => '2019-06-09 15:04:08',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Poster',
                'url' => '/admin/posters',
                'target' => '_self',
                'icon_class' => 'voyager-bookmark',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2019-05-09 10:49:53',
                'updated_at' => '2019-06-10 21:26:49',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Gallery',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-photos',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2019-05-09 10:50:35',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Scolarships',
                'url' => '/admin/scholarships',
                'target' => '_self',
                'icon_class' => 'voyager-study',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2019-05-09 10:51:56',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Video Gallery',
                'url' => '/admin/videos',
                'target' => '_self',
                'icon_class' => 'voyager-video',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2019-05-09 10:52:45',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Partner',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2019-05-09 11:12:43',
                'updated_at' => '2019-06-10 21:26:49',
                'route' => NULL,
                'parameters' => '',
            ),
            28 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Khmer NLP Lab',
                'url' => '/admin/research/khmer-nlp-lab',
                'target' => '_self',
                'icon_class' => 'voyager-edit',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 1,
                'created_at' => '2019-05-09 11:15:48',
                'updated_at' => '2019-05-09 11:15:59',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'DADS Lab',
                'url' => '/admin/research/dads-lab',
                'target' => '_self',
                'icon_class' => 'voyager-lab',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 2,
                'created_at' => '2019-05-09 11:16:34',
                'updated_at' => '2019-05-09 11:17:34',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Publication',
                'url' => '/admin/research/publication',
                'target' => '_self',
                'icon_class' => 'voyager-megaphone',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 3,
                'created_at' => '2019-05-09 11:17:10',
                'updated_at' => '2019-05-09 11:17:17',
                'route' => NULL,
                'parameters' => '',
            ),
            31 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Software/Tools',
                'url' => '/admin/research/software-tool',
                'target' => '_self',
                'icon_class' => 'voyager-lightbulb',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 4,
                'created_at' => '2019-05-09 11:18:37',
                'updated_at' => '2019-05-09 11:18:50',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Researchers',
                'url' => '/admin/research/researchers',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => '#000000',
                'parent_id' => 24,
                'order' => 5,
                'created_at' => '2019-05-09 11:19:21',
                'updated_at' => '2019-05-09 11:19:29',
                'route' => NULL,
                'parameters' => '',
            ),
            33 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Awardees',
                'url' => '/admin/awardee',
                'target' => '_self',
                'icon_class' => 'voyager-trophy',
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 4,
                'created_at' => '2019-05-09 11:26:22',
                'updated_at' => '2019-08-29 05:48:20',
                'route' => NULL,
                'parameters' => '',
            ),
            34 => 
            array (
                'id' => 42,
                'menu_id' => 1,
                'title' => 'Photo Albums',
                'url' => '/admin/photo-albums',
                'target' => '_self',
                'icon_class' => 'voyager-photos',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2019-05-10 12:00:49',
                'updated_at' => '2019-05-10 12:01:09',
                'route' => NULL,
                'parameters' => '',
            ),
            35 => 
            array (
                'id' => 43,
                'menu_id' => 1,
                'title' => 'About GIC',
                'url' => '/admin/about-gic',
                'target' => '_self',
                'icon_class' => 'voyager-question',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2019-05-17 13:55:27',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => NULL,
                'parameters' => '',
            ),
            36 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Alumni/student\'s Message',
                'url' => '/admin/student-message',
                'target' => '_self',
                'icon_class' => 'voyager-bubble-hear',
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 5,
                'created_at' => '2019-05-18 20:31:37',
                'updated_at' => '2019-08-29 05:48:20',
                'route' => NULL,
                'parameters' => '',
            ),
            37 => 
            array (
                'id' => 46,
                'menu_id' => 1,
                'title' => 'Important Links',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paperclip',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2019-05-24 16:18:32',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => 'voyager.important-link.index',
                'parameters' => 'null',
            ),
            38 => 
            array (
                'id' => 47,
                'menu_id' => 1,
                'title' => 'Staff\'s registration',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 22,
                'order' => 1,
                'created_at' => '2019-05-29 22:19:49',
                'updated_at' => '2019-06-04 22:39:30',
                'route' => 'voyager.staffs.index',
                'parameters' => 'null',
            ),
            39 => 
            array (
                'id' => 48,
                'menu_id' => 1,
                'title' => 'Staff\'s Missions',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-milestone',
                'color' => '#000000',
                'parent_id' => 22,
                'order' => 2,
                'created_at' => '2019-05-29 22:20:08',
                'updated_at' => '2019-06-04 22:40:13',
                'route' => 'voyager.missions.index',
                'parameters' => 'null',
            ),
            40 => 
            array (
                'id' => 49,
                'menu_id' => 1,
                'title' => 'Countries',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => '#000000',
                'parent_id' => 10,
                'order' => 1,
                'created_at' => '2019-05-29 22:20:17',
                'updated_at' => '2019-08-29 05:48:13',
                'route' => 'voyager.country.index',
                'parameters' => 'null',
            ),
            41 => 
            array (
                'id' => 50,
                'menu_id' => 1,
                'title' => 'Funders',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-plus',
                'color' => '#000000',
                'parent_id' => 10,
                'order' => 2,
                'created_at' => '2019-05-29 22:20:27',
                'updated_at' => '2019-08-29 05:48:13',
                'route' => 'voyager.funders.index',
                'parameters' => 'null',
            ),
            42 => 
            array (
                'id' => 52,
                'menu_id' => 1,
                'title' => 'Our Product',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 6,
                'created_at' => '2019-05-31 13:49:35',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => 'voyager.products.index',
                'parameters' => 'null',
            ),
            43 => 
            array (
                'id' => 53,
                'menu_id' => 1,
                'title' => 'Contact Us',
                'url' => '/admin/contactus-message',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2019-06-01 00:07:20',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => NULL,
                'parameters' => '',
            ),
            44 => 
            array (
                'id' => 54,
                'menu_id' => 1,
                'title' => 'Degree',
                'url' => '/admin/degrees',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 1,
                'created_at' => '2019-06-01 21:34:40',
                'updated_at' => '2019-06-09 12:30:51',
                'route' => NULL,
                'parameters' => '',
            ),
            45 => 
            array (
                'id' => 55,
                'menu_id' => 1,
                'title' => 'Program Year',
                'url' => '/admin/program-years',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 2,
                'created_at' => '2019-06-01 21:35:17',
                'updated_at' => '2019-06-01 21:36:04',
                'route' => NULL,
                'parameters' => '',
            ),
            46 => 
            array (
                'id' => 56,
                'menu_id' => 1,
                'title' => 'Field of Study/GIC\'s Program',
                'url' => '/admin/field-studies',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 3,
                'created_at' => '2019-06-01 21:35:33',
                'updated_at' => '2019-06-13 21:11:10',
                'route' => NULL,
                'parameters' => '',
            ),
            47 => 
            array (
                'id' => 58,
                'menu_id' => 1,
                'title' => 'Academic Years',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 23,
                'created_at' => '2019-06-07 16:41:49',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => 'voyager.academic-years.index',
                'parameters' => NULL,
            ),
            48 => 
            array (
                'id' => 59,
                'menu_id' => 1,
                'title' => 'GIC Project',
                'url' => '/admin/gic-projects',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => 25,
                'order' => 1,
                'created_at' => '2019-06-09 15:03:49',
                'updated_at' => '2019-06-09 15:04:22',
                'route' => NULL,
                'parameters' => '',
            ),
            49 => 
            array (
                'id' => 60,
                'menu_id' => 1,
                'title' => 'Faq Sub Type',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 62,
                'order' => 2,
                'created_at' => '2019-06-09 20:15:34',
                'updated_at' => '2019-08-29 06:44:36',
                'route' => 'voyager.faq-types.index',
                'parameters' => 'null',
            ),
            50 => 
            array (
                'id' => 61,
                'menu_id' => 1,
                'title' => 'Faqs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 62,
                'order' => 3,
                'created_at' => '2019-06-09 20:16:21',
                'updated_at' => '2019-08-29 06:44:55',
                'route' => 'voyager.faqs2.index',
                'parameters' => 'null',
            ),
            51 => 
            array (
                'id' => 62,
                'menu_id' => 1,
                'title' => 'FAQs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-06-09 20:19:02',
                'updated_at' => '2019-06-10 21:26:49',
                'route' => NULL,
                'parameters' => '',
            ),
            52 => 
            array (
                'id' => 64,
                'menu_id' => 1,
                'title' => 'Future Students',
                'url' => '/admin/future-students',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 3,
                'created_at' => '2019-06-10 14:53:16',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => NULL,
                'parameters' => '',
            ),
            53 => 
            array (
                'id' => 65,
                'menu_id' => 1,
                'title' => 'Teaching Methodology',
                'url' => '/admin/teaching-methodology',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 4,
                'created_at' => '2019-06-10 14:53:49',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => NULL,
                'parameters' => '',
            ),
            54 => 
            array (
                'id' => 66,
                'menu_id' => 1,
                'title' => 'Career Opportunities',
                'url' => '/admin/career-opportunities',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 5,
                'created_at' => '2019-06-10 14:54:33',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => NULL,
                'parameters' => '',
            ),
            55 => 
            array (
                'id' => 67,
                'menu_id' => 1,
                'title' => 'Our Service',
                'url' => '/admin/our-services',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 7,
                'created_at' => '2019-06-10 14:54:50',
                'updated_at' => '2019-08-28 14:55:13',
                'route' => NULL,
                'parameters' => '',
            ),
            56 => 
            array (
                'id' => 68,
                'menu_id' => 1,
                'title' => 'Awardees',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 24,
                'created_at' => '2019-06-13 01:58:54',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => 'voyager.awardee.index',
                'parameters' => NULL,
            ),
            57 => 
            array (
                'id' => 69,
                'menu_id' => 1,
                'title' => 'Content\'s Section',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-window-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2019-06-13 11:25:43',
                'updated_at' => '2019-08-28 14:55:30',
                'route' => 'voyager.site-contents.index',
                'parameters' => 'null',
            ),
            58 => 
            array (
                'id' => 70,
                'menu_id' => 1,
                'title' => 'Homepage Slide Show',
                'url' => '/admin/slide-shows',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 25,
                'created_at' => '2019-06-13 11:53:14',
                'updated_at' => '2019-08-29 05:48:11',
                'route' => NULL,
                'parameters' => '',
            ),
            59 => 
            array (
                'id' => 71,
                'menu_id' => 1,
                'title' => 'Invited Professors',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 26,
                'created_at' => '2019-06-16 19:19:23',
                'updated_at' => '2019-08-29 05:48:11',
                'route' => 'voyager.invited-professors.index',
                'parameters' => NULL,
            ),
            60 => 
            array (
                'id' => 72,
                'menu_id' => 1,
                'title' => 'Aluminuses',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 27,
                'created_at' => '2019-06-16 19:37:03',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.aluminus.index',
                'parameters' => NULL,
            ),
            61 => 
            array (
                'id' => 73,
                'menu_id' => 1,
                'title' => 'Gratuated Years',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 28,
                'created_at' => '2019-06-16 19:37:21',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.gratuated-year.index',
                'parameters' => NULL,
            ),
            62 => 
            array (
                'id' => 74,
                'menu_id' => 1,
                'title' => 'Calendars',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 29,
                'created_at' => '2019-08-11 15:44:06',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.calendar.index',
                'parameters' => NULL,
            ),
            63 => 
            array (
                'id' => 75,
                'menu_id' => 1,
                'title' => 'Timetables',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 30,
                'created_at' => '2019-08-11 15:48:57',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.timetable.index',
                'parameters' => NULL,
            ),
            64 => 
            array (
                'id' => 76,
                'menu_id' => 1,
                'title' => 'Report Slides',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 31,
                'created_at' => '2019-08-11 15:50:02',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.report-slide.index',
                'parameters' => NULL,
            ),
            65 => 
            array (
                'id' => 77,
                'menu_id' => 1,
                'title' => 'Gic Services',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 32,
                'created_at' => '2019-08-12 13:26:58',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.gic-service.index',
                'parameters' => NULL,
            ),
            66 => 
            array (
                'id' => 78,
                'menu_id' => 1,
                'title' => 'Gic Service Counters',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 33,
                'created_at' => '2019-08-12 13:33:47',
                'updated_at' => '2019-08-29 08:08:42',
                'route' => 'voyager.gic-service-counter.index',
                'parameters' => NULL,
            ),
            67 => 
            array (
                'id' => 79,
                'menu_id' => 1,
                'title' => 'Promotion Years',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => '#000000',
                'parent_id' => 20,
                'order' => 2,
                'created_at' => '2019-08-28 14:53:59',
                'updated_at' => '2019-08-28 14:59:27',
                'route' => 'voyager.promotion-years.index',
                'parameters' => 'null',
            ),
            68 => 
            array (
                'id' => 80,
                'menu_id' => 1,
                'title' => 'Student Project Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => 25,
                'order' => 2,
                'created_at' => '2019-08-29 02:04:58',
                'updated_at' => '2019-08-29 08:19:04',
                'route' => 'voyager.student-project-type.index',
                'parameters' => 'null',
            ),
            69 => 
            array (
                'id' => 81,
                'menu_id' => 1,
                'title' => 'Student Projects',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => 25,
                'order' => 3,
                'created_at' => '2019-08-29 02:06:01',
                'updated_at' => '2019-08-29 08:19:16',
                'route' => 'voyager.student-project.index',
                'parameters' => 'null',
            ),
            70 => 
            array (
                'id' => 82,
                'menu_id' => 1,
                'title' => 'Faq Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => 62,
                'order' => 1,
                'created_at' => '2019-08-29 05:47:03',
                'updated_at' => '2019-08-29 06:44:25',
                'route' => 'voyager.faq-parent-types.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}