<?php

use Illuminate\Database\Seeder;

class GeneratedDataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-08-13 08:45:36',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-03-07 21:36:16',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-03-07 21:36:16',
                'updated_at' => '2019-03-07 21:36:16',
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'students_projects',
                'slug' => 'students-projects',
                'display_name_singular' => 'Students Project',
                'display_name_plural' => 'Students Projects',
                'icon' => 'voyager-paper-plane',
                'model_name' => 'App\\StudentsProject',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-03 19:41:14',
                'updated_at' => '2019-05-03 19:41:14',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'about_us',
                'slug' => 'about-us',
                'display_name_singular' => 'About U',
                'display_name_plural' => 'About Us',
                'icon' => NULL,
                'model_name' => 'App\\AboutUs',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-05-03 19:41:14',
                'updated_at' => '2019-05-03 19:41:14',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'contact_us',
                'slug' => 'contact-us',
                'display_name_singular' => 'Contact U',
                'display_name_plural' => 'Contact Us',
                'icon' => NULL,
                'model_name' => 'App\\ContactUs',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-03 19:41:14',
                'updated_at' => '2019-08-11 16:38:29',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'scholarship',
                'slug' => 'scholarship',
                'display_name_singular' => 'Scholarship',
                'display_name_plural' => 'Scholarships',
                'icon' => NULL,
                'model_name' => 'App\\Scholarship',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-03 19:41:14',
                'updated_at' => '2019-05-03 19:41:14',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'contactus_message',
                'slug' => 'contactus-message',
                'display_name_singular' => 'Contactus Message',
                'display_name_plural' => 'Contactus Messages',
                'icon' => NULL,
                'model_name' => 'App\\ContactusMessage',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-04-03 12:18:54',
                'updated_at' => '2019-07-07 23:24:19',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'about_us_link',
                'slug' => 'about-us-link',
                'display_name_singular' => 'About Us Link',
                'display_name_plural' => 'About Us Links',
                'icon' => NULL,
                'model_name' => 'App\\AboutUsLink',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-05-03 19:41:14',
                'updated_at' => '2019-05-03 19:41:14',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'partner_types',
                'slug' => 'partner-types',
                'display_name_singular' => 'Partner Type',
                'display_name_plural' => 'Partner Types',
                'icon' => 'voyager-documentation',
                'model_name' => 'App\\PartnerType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-08 12:05:08',
                'updated_at' => '2019-05-08 12:05:08',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'partner2',
                'slug' => 'partner2',
                'display_name_singular' => 'Partner',
                'display_name_plural' => 'Partners',
                'icon' => 'voyager-group',
                'model_name' => 'App\\Partner2',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"created_at","order_display_column":"name","order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-08 12:05:08',
                'updated_at' => '2019-05-09 14:09:27',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'slide_shows',
                'slug' => 'slide-shows',
                'display_name_singular' => 'Slide Show',
                'display_name_plural' => 'Slide Shows',
                'icon' => NULL,
                'model_name' => 'App\\SlideShow',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-09 10:58:44',
                'updated_at' => '2019-06-13 11:53:49',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'events',
                'slug' => 'events',
                'display_name_singular' => 'Seminar',
                'display_name_plural' => 'Seminars',
                'icon' => NULL,
                'model_name' => 'App\\Event',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-09 14:13:33',
                'updated_at' => '2019-05-09 15:27:34',
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'photo_albums',
                'slug' => 'photo-albums',
                'display_name_singular' => 'Photo Album',
                'display_name_plural' => 'Photo Albums',
                'icon' => 'voyager-photos',
                'model_name' => 'App\\PhotoAlbum',
                'policy_name' => NULL,
                'controller' => 'App\\Http\\Controllers\\Backend\\PhotoAlbumController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-10 12:01:46',
                'updated_at' => '2019-05-16 08:30:15',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'photos',
                'slug' => 'photos',
                'display_name_singular' => 'Photo',
                'display_name_plural' => 'Photos',
                'icon' => 'voyager-photo',
                'model_name' => 'App\\Photo',
                'policy_name' => NULL,
                'controller' => 'App\\Http\\Controllers\\Backend\\PhotoController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-10 12:01:46',
                'updated_at' => '2019-05-19 14:37:09',
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'news',
                'slug' => 'news',
                'display_name_singular' => 'News',
                'display_name_plural' => 'News',
                'icon' => NULL,
                'model_name' => 'App\\News',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-17 13:44:56',
                'updated_at' => '2019-08-28 08:23:31',
            ),
            16 => 
            array (
                'id' => 19,
                'name' => 'about_gic',
                'slug' => 'about-gic',
                'display_name_singular' => 'About Gic',
                'display_name_plural' => 'About Gics',
                'icon' => NULL,
                'model_name' => 'App\\AboutGic',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-17 13:44:56',
                'updated_at' => '2019-05-17 13:44:56',
            ),
            17 => 
            array (
                'id' => 20,
                'name' => 'student_message',
                'slug' => 'student-message',
                'display_name_singular' => 'Alumni/student\'s Message',
                'display_name_plural' => 'Student Messages',
                'icon' => NULL,
                'model_name' => 'App\\StudentMessage',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-18 20:33:06',
                'updated_at' => '2019-05-20 21:26:48',
            ),
            18 => 
            array (
                'id' => 23,
                'name' => 'scholarships',
                'slug' => 'scholarships',
                'display_name_singular' => 'Scholarships',
                'display_name_plural' => 'Scholarships',
                'icon' => NULL,
                'model_name' => 'App\\Scholarships',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-21 14:31:04',
                'updated_at' => '2019-05-21 15:38:17',
            ),
            19 => 
            array (
                'id' => 24,
                'name' => 'important_link',
                'slug' => 'important-link',
                'display_name_singular' => 'Important Link',
                'display_name_plural' => 'Important Links',
                'icon' => NULL,
                'model_name' => 'App\\ImportantLink',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-05-24 16:18:32',
                'updated_at' => '2019-05-24 16:18:32',
            ),
            20 => 
            array (
                'id' => 25,
                'name' => 'staffs',
                'slug' => 'staffs',
                'display_name_singular' => 'Staff',
                'display_name_plural' => 'Staff',
                'icon' => NULL,
                'model_name' => 'App\\Staff',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-29 22:19:49',
                'updated_at' => '2019-07-24 06:19:09',
            ),
            21 => 
            array (
                'id' => 26,
                'name' => 'missions',
                'slug' => 'missions',
                'display_name_singular' => 'Mission',
                'display_name_plural' => 'Missions',
                'icon' => NULL,
                'model_name' => 'App\\Mission',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-29 22:20:08',
                'updated_at' => '2019-06-07 16:07:07',
            ),
            22 => 
            array (
                'id' => 27,
                'name' => 'country',
                'slug' => 'country',
                'display_name_singular' => 'Country',
                'display_name_plural' => 'Countries',
                'icon' => NULL,
                'model_name' => 'App\\Country',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-05-29 22:20:17',
                'updated_at' => '2019-05-31 16:21:34',
            ),
            23 => 
            array (
                'id' => 28,
                'name' => 'funders',
                'slug' => 'funders',
                'display_name_singular' => 'Funder',
                'display_name_plural' => 'Funders',
                'icon' => NULL,
                'model_name' => 'App\\Funder',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-05-29 22:20:27',
                'updated_at' => '2019-05-29 22:20:27',
            ),
            24 => 
            array (
                'id' => 30,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => NULL,
                'model_name' => 'App\\Product',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-05-31 13:49:35',
                'updated_at' => '2019-05-31 13:49:35',
            ),
            25 => 
            array (
                'id' => 32,
                'name' => 'degrees',
                'slug' => 'degrees',
                'display_name_singular' => 'Degree',
                'display_name_plural' => 'Degrees',
                'icon' => NULL,
                'model_name' => 'App\\Degree',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-06-01 21:33:04',
                'updated_at' => '2019-06-01 21:33:04',
            ),
            26 => 
            array (
                'id' => 33,
                'name' => 'program_years',
                'slug' => 'program-years',
                'display_name_singular' => 'Program Year',
                'display_name_plural' => 'Program Years',
                'icon' => NULL,
                'model_name' => 'App\\ProgramYear',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-06-01 21:33:04',
                'updated_at' => '2019-06-01 21:33:04',
            ),
            27 => 
            array (
                'id' => 34,
                'name' => 'field_studies',
                'slug' => 'field-studies',
                'display_name_singular' => 'Field of Study/GIC\'s Program',
                'display_name_plural' => 'Field of Study/GIC\'s Program',
                'icon' => NULL,
                'model_name' => 'App\\FieldStudy',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-01 21:33:04',
                'updated_at' => '2019-06-13 21:10:20',
            ),
            28 => 
            array (
                'id' => 35,
                'name' => 'curriculums',
                'slug' => 'curriculums',
                'display_name_singular' => 'Curriculum',
                'display_name_plural' => 'Curriculums',
                'icon' => NULL,
                'model_name' => 'App\\Curriculum',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-01 21:33:04',
                'updated_at' => '2019-06-01 21:33:04',
            ),
            29 => 
            array (
                'id' => 36,
                'name' => 'academic_years',
                'slug' => 'academic-years',
                'display_name_singular' => 'Academic Year',
                'display_name_plural' => 'Academic Years',
                'icon' => NULL,
                'model_name' => 'App\\AcademicYear',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-07 16:41:49',
                'updated_at' => '2019-06-22 22:56:55',
            ),
            30 => 
            array (
                'id' => 37,
                'name' => 'gic_projects',
                'slug' => 'gic-projects',
                'display_name_singular' => 'Gic Project',
                'display_name_plural' => 'Gic Projects',
                'icon' => NULL,
                'model_name' => 'App\\GicProject',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-09 15:04:33',
                'updated_at' => '2019-08-14 07:53:21',
            ),
            31 => 
            array (
                'id' => 38,
                'name' => 'faq_types',
                'slug' => 'faq-types',
                'display_name_singular' => 'Faq Sub Type',
                'display_name_plural' => 'Faq Sub Types',
                'icon' => 'voyager-paperclip',
                'model_name' => 'App\\FaqType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-09 20:15:34',
                'updated_at' => '2019-08-29 06:47:38',
            ),
            32 => 
            array (
                'id' => 39,
                'name' => 'faqs2',
                'slug' => 'faqs2',
                'display_name_singular' => 'Faqs',
                'display_name_plural' => 'Faqs',
                'icon' => 'voyager-paper-plane',
                'model_name' => 'App\\Faqs2',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-09 20:16:21',
                'updated_at' => '2019-08-29 06:47:22',
            ),
            33 => 
            array (
                'id' => 40,
                'name' => 'staff_position',
                'slug' => 'staff-position',
                'display_name_singular' => 'Staff Position',
                'display_name_plural' => 'Staff Positions',
                'icon' => NULL,
                'model_name' => 'App\\StaffPosition',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-09 21:40:07',
                'updated_at' => '2019-08-05 06:57:41',
            ),
            34 => 
            array (
                'id' => 41,
                'name' => 'posters',
                'slug' => 'posters',
                'display_name_singular' => 'Poster',
                'display_name_plural' => 'Posters',
                'icon' => NULL,
                'model_name' => 'App\\Poster',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-06-10 15:18:59',
                'updated_at' => '2019-06-10 15:18:59',
            ),
            35 => 
            array (
                'id' => 42,
                'name' => 'awardee',
                'slug' => 'awardee',
                'display_name_singular' => 'Awardee',
                'display_name_plural' => 'Awardees',
                'icon' => NULL,
                'model_name' => 'App\\Awardee',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-13 01:58:54',
                'updated_at' => '2019-06-22 23:30:07',
            ),
            36 => 
            array (
                'id' => 43,
                'name' => 'site_contents',
                'slug' => 'site-contents',
                'display_name_singular' => 'Content\'s Section',
                'display_name_plural' => 'Content\'s Sections',
                'icon' => NULL,
                'model_name' => 'App\\SiteContent',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-13 11:25:43',
                'updated_at' => '2019-06-22 14:45:31',
            ),
            37 => 
            array (
                'id' => 45,
                'name' => 'invited_professors',
                'slug' => 'invited-professors',
                'display_name_singular' => 'Invited Professor',
                'display_name_plural' => 'Invited Professors',
                'icon' => NULL,
                'model_name' => 'App\\InvitedProfessor',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-16 19:19:23',
                'updated_at' => '2019-06-22 21:31:23',
            ),
            38 => 
            array (
                'id' => 46,
                'name' => 'aluminus',
                'slug' => 'aluminus',
                'display_name_singular' => 'Aluminus',
                'display_name_plural' => 'Aluminuses',
                'icon' => NULL,
                'model_name' => 'App\\Aluminus',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-06-16 19:37:03',
                'updated_at' => '2019-08-28 14:57:20',
            ),
            39 => 
            array (
                'id' => 47,
                'name' => 'gratuated_year',
                'slug' => 'gratuated-year',
                'display_name_singular' => 'Gratuated Year',
                'display_name_plural' => 'Gratuated Years',
                'icon' => NULL,
                'model_name' => 'App\\GratuatedYear',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-06-16 19:37:21',
                'updated_at' => '2019-06-16 19:37:21',
            ),
            40 => 
            array (
                'id' => 48,
                'name' => 'videos',
                'slug' => 'videos',
                'display_name_singular' => 'Video',
                'display_name_plural' => 'Videos',
                'icon' => NULL,
                'model_name' => 'App\\Video',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 0,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-06-19 15:52:08',
                'updated_at' => '2019-06-19 15:52:08',
            ),
            41 => 
            array (
                'id' => 49,
                'name' => 'calendar',
                'slug' => 'calendar',
                'display_name_singular' => 'Calendar',
                'display_name_plural' => 'Calendars',
                'icon' => NULL,
                'model_name' => 'App\\Calendar',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-08-11 15:44:06',
                'updated_at' => '2019-08-11 15:44:55',
            ),
            42 => 
            array (
                'id' => 50,
                'name' => 'timetable',
                'slug' => 'timetable',
                'display_name_singular' => 'Timetable',
                'display_name_plural' => 'Timetables',
                'icon' => NULL,
                'model_name' => 'App\\Timetable',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-08-11 15:48:57',
                'updated_at' => '2019-08-11 15:48:57',
            ),
            43 => 
            array (
                'id' => 51,
                'name' => 'report_slide',
                'slug' => 'report-slide',
                'display_name_singular' => 'Report Slide',
                'display_name_plural' => 'Report Slides',
                'icon' => NULL,
                'model_name' => 'App\\ReportSlide',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-08-11 15:50:02',
                'updated_at' => '2019-08-11 15:50:02',
            ),
            44 => 
            array (
                'id' => 52,
                'name' => 'gic_service',
                'slug' => 'gic-service',
                'display_name_singular' => 'Gic Service',
                'display_name_plural' => 'Gic Services',
                'icon' => NULL,
                'model_name' => 'App\\GicService',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-08-12 13:26:58',
                'updated_at' => '2019-08-12 13:32:01',
            ),
            45 => 
            array (
                'id' => 53,
                'name' => 'gic_service_counter',
                'slug' => 'gic-service-counter',
                'display_name_singular' => 'Gic Service Counter',
                'display_name_plural' => 'Gic Service Counters',
                'icon' => NULL,
                'model_name' => 'App\\GicServiceCounter',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-08-12 13:33:47',
                'updated_at' => '2019-08-12 13:33:47',
            ),
            46 => 
            array (
                'id' => 54,
                'name' => 'promotion_years',
                'slug' => 'promotion-years',
                'display_name_singular' => 'Promotion Year',
                'display_name_plural' => 'Promotion Years',
                'icon' => NULL,
                'model_name' => 'App\\PromotionYear',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-08-28 14:53:59',
                'updated_at' => '2019-08-28 14:53:59',
            ),
            47 => 
            array (
                'id' => 55,
                'name' => 'student_project_type',
                'slug' => 'student-project-type',
                'display_name_singular' => 'Student Project Type',
                'display_name_plural' => 'Student Project Types',
                'icon' => NULL,
                'model_name' => 'App\\StudentProjectType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-08-29 02:04:58',
                'updated_at' => '2019-08-29 02:04:58',
            ),
            48 => 
            array (
                'id' => 56,
                'name' => 'student_project',
                'slug' => 'student-project',
                'display_name_singular' => 'Student Project',
                'display_name_plural' => 'Student Projects',
                'icon' => NULL,
                'model_name' => 'App\\StudentProject',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-08-29 02:06:01',
                'updated_at' => '2019-08-29 02:07:34',
            ),
            49 => 
            array (
                'id' => 57,
                'name' => 'faq_parent_types',
                'slug' => 'faq-parent-types',
                'display_name_singular' => 'Faq Type',
                'display_name_plural' => 'Faq Types',
                'icon' => NULL,
                'model_name' => 'App\\FaqParentType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2019-08-29 05:47:03',
                'updated_at' => '2019-08-29 06:47:32',
            ),
        ));
        
        
    }
}