<?php

use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menuItems = [
            [
              "id" => 1,
              "menu_id" => 1,
              "title" => "Dashboard",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-boat",
              "color" => null,
              "parent_id" => null,
              "order" => 1,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-03-07 14:36:16",
              "route" => "voyager.dashboard",
              "parameters" => null,
            ],
            [
              "id" => 2,
              "menu_id" => 1,
              "title" => "Media",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-images",
              "color" => null,
              "parent_id" => null,
              "order" => 17,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => "voyager.media.index",
              "parameters" => null,
            ],
            [
              "id" => 3,
              "menu_id" => 1,
              "title" => "Users",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-person",
              "color" => null,
              "parent_id" => null,
              "order" => 3,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-03-07 14:36:16",
              "route" => "voyager.users.index",
              "parameters" => null,
            ],
            [
              "id" => 4,
              "menu_id" => 1,
              "title" => "Roles",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-lock",
              "color" => null,
              "parent_id" => null,
              "order" => 2,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-03-07 14:36:16",
              "route" => "voyager.roles.index",
              "parameters" => null,
            ],
            [
              "id" => 5,
              "menu_id" => 1,
              "title" => "Tools",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-tools",
              "color" => null,
              "parent_id" => null,
              "order" => 18,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => null,
            ],
            [
              "id" => 6,
              "menu_id" => 1,
              "title" => "Menu Builder",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-list",
              "color" => null,
              "parent_id" => 5,
              "order" => 1,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 03:37:12",
              "route" => "voyager.menus.index",
              "parameters" => null,
            ],
            [
              "id" => 7,
              "menu_id" => 1,
              "title" => "Database",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-data",
              "color" => null,
              "parent_id" => 5,
              "order" => 2,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 03:37:12",
              "route" => "voyager.database.index",
              "parameters" => null,
            ],
            [
              "id" => 8,
              "menu_id" => 1,
              "title" => "Compass",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-compass",
              "color" => null,
              "parent_id" => 5,
              "order" => 3,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 03:37:12",
              "route" => "voyager.compass.index",
              "parameters" => null,
            ],
            [
              "id" => 9,
              "menu_id" => 1,
              "title" => "BREAD",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-bread",
              "color" => null,
              "parent_id" => 5,
              "order" => 4,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 03:37:12",
              "route" => "voyager.bread.index",
              "parameters" => null,
            ],
            [
              "id" => 10,
              "menu_id" => 1,
              "title" => "Settings",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-settings",
              "color" => null,
              "parent_id" => null,
              "order" => 19,
              "created_at" => "2019-03-07 14:36:16",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => "voyager.settings.index",
              "parameters" => null,
            ],
            [
              "id" => 11,
              "menu_id" => 1,
              "title" => "Hooks",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-hook",
              "color" => null,
              "parent_id" => 5,
              "order" => 5,
              "created_at" => "2019-03-07 14:39:40",
              "updated_at" => "2019-05-09 03:37:12",
              "route" => "voyager.hooks",
              "parameters" => null,
            ],
            [
              "id" => 12,
              "menu_id" => 1,
              "title" => "Partner Types",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-documentation",
              "color" => "#000000",
              "parent_id" => 32,
              "order" => 1,
              "created_at" => "2019-05-08 05:05:08",
              "updated_at" => "2019-05-09 04:12:52",
              "route" => "voyager.partner-types.index",
              "parameters" => "null",
            ],
            [
              "id" => 13,
              "menu_id" => 1,
              "title" => "Partner",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-group",
              "color" => "#000000",
              "parent_id" => 32,
              "order" => 2,
              "created_at" => "2019-05-08 05:05:08",
              "updated_at" => "2019-05-09 04:12:59",
              "route" => "voyager.partner2.index",
              "parameters" => "null",
            ],
            [
              "id" => 14,
              "menu_id" => 1,
              "title" => "About GIC",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-question",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 4,
              "created_at" => "2019-05-09 03:35:04",
              "updated_at" => "2019-05-09 03:38:46",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 15,
              "menu_id" => 1,
              "title" => "Social Medias",
              "url" => "/admin/about-us-link",
              "target" => "_self",
              "icon_class" => "voyager-facebook",
              "color" => "#000000",
              "parent_id" => 14,
              "order" => 1,
              "created_at" => "2019-05-09 03:37:05",
              "updated_at" => "2019-05-09 03:37:13",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 16,
              "menu_id" => 1,
              "title" => "About GIC",
              "url" => "/admin/about-us",
              "target" => "_self",
              "icon_class" => "voyager-question",
              "color" => "#000000",
              "parent_id" => 14,
              "order" => 2,
              "created_at" => "2019-05-09 03:38:32",
              "updated_at" => "2019-05-09 03:47:29",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 17,
              "menu_id" => 1,
              "title" => "FAQS",
              "url" => "/admin/faqs",
              "target" => "_self",
              "icon_class" => "voyager-paper-plane",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 14,
              "created_at" => "2019-05-09 03:41:50",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 18,
              "menu_id" => 1,
              "title" => "News",
              "url" => "/admin/news",
              "target" => "_self",
              "icon_class" => "voyager-news",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 11,
              "created_at" => "2019-05-09 03:42:30",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 19,
              "menu_id" => 1,
              "title" => "Seminars",
              "url" => "/admin/events",
              "target" => "_self",
              "icon_class" => "voyager-tv",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 12,
              "created_at" => "2019-05-09 03:43:46",
              "updated_at" => "2019-05-09 04:20:13",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 20,
              "menu_id" => 1,
              "title" => "Students & Alumni",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-people",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 10,
              "created_at" => "2019-05-09 03:44:38",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 21,
              "menu_id" => 1,
              "title" => "Alumni",
              "url" => "/admin/alumni",
              "target" => "_self",
              "icon_class" => "voyager-people",
              "color" => "#000000",
              "parent_id" => 20,
              "order" => 1,
              "created_at" => "2019-05-09 03:44:58",
              "updated_at" => "2019-05-09 03:45:02",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 22,
              "menu_id" => 1,
              "title" => "Faculty & Staff",
              "url" => "/admin/faculty-and-staff",
              "target" => "_self",
              "icon_class" => "voyager-people",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 5,
              "created_at" => "2019-05-09 03:46:10",
              "updated_at" => "2019-05-09 04:13:53",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 23,
              "menu_id" => 1,
              "title" => "Academic Programs",
              "url" => "/admin/academic-program",
              "target" => "_self",
              "icon_class" => "voyager-calendar",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 6,
              "created_at" => "2019-05-09 03:46:40",
              "updated_at" => "2019-05-09 04:14:15",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 24,
              "menu_id" => 1,
              "title" => "GIC Research",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-lab",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 7,
              "created_at" => "2019-05-09 03:47:07",
              "updated_at" => "2019-05-09 03:47:46",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 25,
              "menu_id" => 1,
              "title" => "Projects",
              "url" => "/admin/projects",
              "target" => "_self",
              "icon_class" => "voyager-bag",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 8,
              "created_at" => "2019-05-09 03:48:33",
              "updated_at" => "2019-05-09 04:19:50",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 26,
              "menu_id" => 1,
              "title" => "Poster",
              "url" => "/admin/posters",
              "target" => "_self",
              "icon_class" => "voyager-bookmark",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 13,
              "created_at" => "2019-05-09 03:49:53",
              "updated_at" => "2019-05-09 04:21:29",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 27,
              "menu_id" => 1,
              "title" => "Gallery",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-photos",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 15,
              "created_at" => "2019-05-09 03:50:35",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 28,
              "menu_id" => 1,
              "title" => "Scolarships",
              "url" => "/admin/scholarships",
              "target" => "_self",
              "icon_class" => "voyager-study",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 16,
              "created_at" => "2019-05-09 03:51:56",
              "updated_at" => "2019-05-09 04:22:25",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 29,
              "menu_id" => 1,
              "title" => "Video Gallery",
              "url" => "/admin/gallery/videos",
              "target" => "_self",
              "icon_class" => "voyager-video",
              "color" => "#000000",
              "parent_id" => 27,
              "order" => 1,
              "created_at" => "2019-05-09 03:52:45",
              "updated_at" => "2019-05-09 04:21:55",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 30,
              "menu_id" => 1,
              "title" => "Photo Gallery",
              "url" => "/admin/gallery/photo",
              "target" => "_self",
              "icon_class" => "voyager-photo",
              "color" => "#000000",
              "parent_id" => 27,
              "order" => 2,
              "created_at" => "2019-05-09 03:53:14",
              "updated_at" => "2019-05-09 04:22:10",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 32,
              "menu_id" => 1,
              "title" => "Partner",
              "url" => "",
              "target" => "_self",
              "icon_class" => "voyager-company",
              "color" => "#000000",
              "parent_id" => null,
              "order" => 9,
              "created_at" => "2019-05-09 04:12:43",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 33,
              "menu_id" => 1,
              "title" => "Khmer NLP Lab",
              "url" => "/admin/research/khmer-nlp-lab",
              "target" => "_self",
              "icon_class" => "voyager-edit",
              "color" => "#000000",
              "parent_id" => 24,
              "order" => 1,
              "created_at" => "2019-05-09 04:15:48",
              "updated_at" => "2019-05-09 04:15:59",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 34,
              "menu_id" => 1,
              "title" => "DADS Lab",
              "url" => "/admin/research/dads-lab",
              "target" => "_self",
              "icon_class" => "voyager-lab",
              "color" => "#000000",
              "parent_id" => 24,
              "order" => 2,
              "created_at" => "2019-05-09 04:16:34",
              "updated_at" => "2019-05-09 04:17:34",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 35,
              "menu_id" => 1,
              "title" => "Publication",
              "url" => "/admin/research/publication",
              "target" => "_self",
              "icon_class" => "voyager-megaphone",
              "color" => "#000000",
              "parent_id" => 24,
              "order" => 3,
              "created_at" => "2019-05-09 04:17:10",
              "updated_at" => "2019-05-09 04:17:17",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 36,
              "menu_id" => 1,
              "title" => "Software/Tools",
              "url" => "/admin/research/software-tool",
              "target" => "_self",
              "icon_class" => "voyager-lightbulb",
              "color" => "#000000",
              "parent_id" => 24,
              "order" => 4,
              "created_at" => "2019-05-09 04:18:37",
              "updated_at" => "2019-05-09 04:18:50",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 37,
              "menu_id" => 1,
              "title" => "Researchers",
              "url" => "/admin/research/researchers",
              "target" => "_self",
              "icon_class" => "voyager-group",
              "color" => "#000000",
              "parent_id" => 24,
              "order" => 5,
              "created_at" => "2019-05-09 04:19:21",
              "updated_at" => "2019-05-09 04:19:29",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 38,
              "menu_id" => 1,
              "title" => "Current Students",
              "url" => "/admin/current-students",
              "target" => "_self",
              "icon_class" => "voyager-people",
              "color" => "#000000",
              "parent_id" => 20,
              "order" => 2,
              "created_at" => "2019-05-09 04:23:30",
              "updated_at" => "2019-05-09 04:23:39",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 39,
              "menu_id" => 1,
              "title" => "Student's Products",
              "url" => "/admin/student-products",
              "target" => "_self",
              "icon_class" => "voyager-tools",
              "color" => "#000000",
              "parent_id" => 20,
              "order" => 3,
              "created_at" => "2019-05-09 04:24:17",
              "updated_at" => "2019-05-09 04:24:28",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 40,
              "menu_id" => 1,
              "title" => "Awardees",
              "url" => "/admin/awardees.",
              "target" => "_self",
              "icon_class" => "voyager-trophy",
              "color" => "#000000",
              "parent_id" => 20,
              "order" => 4,
              "created_at" => "2019-05-09 04:26:22",
              "updated_at" => "2019-05-09 04:26:33",
              "route" => null,
              "parameters" => "",
            ],
            [
              "id" => 41,
              "menu_id" => 1,
              "title" => "Alumni's Message",
              "url" => "/admin/alumni-message",
              "target" => "_self",
              "icon_class" => "voyager-bubble-hear",
              "color" => "#000000",
              "parent_id" => 20,
              "order" => 5,
              "created_at" => "2019-05-09 04:27:40",
              "updated_at" => "2019-05-09 04:27:50",
              "route" => null,
              "parameters" => "",
            ],
          ];

        App\MenuItem::truncate();
        App\MenuItem::insert($menuItems);
    }
}
